services:
  may-db:
    container_name: may-db
    image: postgres:latest
    env_file:
      - .env
    ports: 
      - "5432:5432"
    volumes: 
      - pgdata:/var/lib/postgressql/data
volumes:
  pgdata: {}